on:
  push:
    branches:
      - "**"  
jobs:
  lint:
    name: Clang-Tidy Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake  clang-tidy build-essential ninja-build pkg-config \
            libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev \
            libgl1-mesa-dev mesa-common-dev \
            libwayland-dev libxkbcommon-dev wayland-protocols

      - name: Configure project
        run: cmake --preset=linux-release

      - name: Run Clang-Tidy
        run: |
          # Find all source/header files
          FILES=$(find src/ -type f \( -name "*.cpp" -o -name "*.cxx" -o -name "*.cc" -o -name "*.c" -o -name "*.h" -o -name "*.hpp" \))
          for f in $FILES; do
            clang-tidy -p build/ "$f"
          done
